seed: 123456
case-dir: "caseSteadyState"
airfoil-database: "airfoil_database"
fixed-airfoil: True
airfoil-name: "elipse"
freestream-angle:
  - -10
  - 10
freestream-length:
  - 0
  - 10
# 流体物性参数

rho: 1
nu: 1e-5
# 并行设置

parallel-enable: True
subdomains: 7
# 后处理

res: 128
output-raw-mesh: True
output-airfoil-boundary: True
# 输出

n-samples: 2
output-dir: "outputs"
output-prefix: "sample"
